---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang}

#caches:
#- path: gopath/

inputs:
  - name: terraform-provider-ci

#outputs:
#  - name: environment

run:
  path: bash
  args:
  - -exc
  - |
    chmod +x terraform-provider-ci/ci/tasks/run-ci.sh
    terraform-provider-ci/ci/tasks/run-ci.sh
params:
  ALICLOUD_ACCESS_KEY: ""
  ALICLOUD_SECRET_KEY: ""
  ALICLOUD_REGION: ""
  TEST_CASE_CODE: ""
  SWEEPER_CODE: ""

